from enum import StrEnum


class RightsReasonCode(StrEnum):
    RIGHTS_NOT_APPROVED = "RIGHTS_NOT_APPROVED"
    RIGHTS_EVIDENCE_MISSING = "RIGHTS_EVIDENCE_MISSING"
    RIGHTS_EXPIRED = "RIGHTS_EXPIRED"
    RIGHTS_REVOKED = "RIGHTS_REVOKED"
    PLATFORM_NOT_ALLOWED = "PLATFORM_NOT_ALLOWED"
    TERRITORY_NOT_ALLOWED = "TERRITORY_NOT_ALLOWED"
    COMMERCIAL_USE_NOT_ALLOWED = "COMMERCIAL_USE_NOT_ALLOWED"
    MODIFICATION_NOT_ALLOWED = "MODIFICATION_NOT_ALLOWED"
    SYNTHETIC_EDIT_NOT_ALLOWED = "SYNTHETIC_EDIT_NOT_ALLOWED"
    ATTRIBUTION_MISSING = "ATTRIBUTION_MISSING"
    UNAPPROVED_MATCH_FOOTAGE = "UNAPPROVED_MATCH_FOOTAGE"
    RIGHTS_NOT_YET_VALID = "RIGHTS_NOT_YET_VALID"
    EDITORIAL_USE_NOT_ALLOWED = "EDITORIAL_USE_NOT_ALLOWED"
    CAMPAIGN_NOT_ALLOWED = "CAMPAIGN_NOT_ALLOWED"
    RIGHTS_REVIEW_DUE = "RIGHTS_REVIEW_DUE"
    MULTIPLE_APPLICABLE_RIGHTS = "MULTIPLE_APPLICABLE_RIGHTS"
    ASSET_UNAVAILABLE = "ASSET_UNAVAILABLE"
    ASSET_HASH_MISMATCH = "ASSET_HASH_MISMATCH"
